### ISSUE TITLE
error in data binding angular 5

### ISSUE THREAD

**Issue by jozifen** [ikedaosushi/tech-news#3216]
hey there ,
I'm working on angular project , so I wanna update a user by transformings his data to a form BUT I keep getting this error all the time:

```
ERROR TypeError: Cannot read property 'cin' of undefined
    at Object.eval [as updateDirective
```
cin is the id of the user
can anybody help me???

**Comment by ikedaosushi** [comment]
Dear jozifen, 

I think you had created wrong repository.
Could you check that? I'll close it for now.
